<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>歸檔送出10</name>
   <tag></tag>
   <elementGuidId>71b69ce9-bcf6-47d8-b736-02bcdaee43c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ant-table-cell.ant-table-cell-fix-right.ant-table-cell-ellipsis.ant-table-cell-row-hover > button.ant-btn.ant-btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='submit-asset-btn-10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c233fb4-b2d8-4cef-88f8-b76798877b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4049ae5a-cacf-4d7c-b063-2a63fcacdc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary</value>
      <webElementGuid>1aa1b444-2c5e-4298-aca0-3e11ac80dd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>送 出</value>
      <webElementGuid>3776016d-8bf0-40ee-8877-83f6786ecbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='submit-asset-btn-10']</value>
      <webElementGuid>1a8c5152-f74f-4cae-9e9e-ca44b046b3b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>4dd98335-be5c-4c91-81f6-8d7be46b569a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div[3]/div/div/div/div/div/div[2]/table/tbody/tr[11]/td[22]/button</value>
      <webElementGuid>c0627a71-ea7e-4493-a1d5-31d0f48ed38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[56]/following::button[3]</value>
      <webElementGuid>4b29d289-7dfe-4766-86be-a440fea22825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[55]/following::button[3]</value>
      <webElementGuid>c9cc5891-f851-4a34-87c0-92f8d5dfc41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='清除勾選'])[1]/preceding::button[1]</value>
      <webElementGuid>6eaf4313-4190-45f0-be54-4f01c3e36bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[22]/button</value>
      <webElementGuid>c6a03baf-4c7d-4144-9e41-c194ae545d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '送 出' or . = '送 出')]</value>
      <webElementGuid>706e88f4-1856-45e6-8bd4-325d5686f43e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
