<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>編輯元數據配對</name>
   <tag></tag>
   <elementGuidId>93dde3e0-fe04-4d1e-b0cd-24a3788fc29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'edit-mapping-btn' and @type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-mapping-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-mapping-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8d8da12-9134-4380-8e2b-5e3f8939c28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-mapping-btn</value>
      <webElementGuid>29eddaca-2444-4432-8112-bce01e384c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a30e477e-88e3-4ce9-a22b-57c64fef99e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-sm</value>
      <webElementGuid>823dafa0-3e04-4c9f-8263-f7b73083faea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>編 輯</value>
      <webElementGuid>197e6303-6264-4dc6-b108-eeca245103ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-mapping-btn&quot;)</value>
      <webElementGuid>25c4755e-d170-4544-818a-4dc6bd6358da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-mapping-btn']</value>
      <webElementGuid>5fd7129d-5710-4aa8-a673-faa95c0793e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>971375e5-4b86-41b8-b295-614e134b1d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據配對'])[1]/following::button[1]</value>
      <webElementGuid>14d39ef9-801f-4007-af0c-644b59e196c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共 3 筆資料'])[1]/following::button[3]</value>
      <webElementGuid>8ef1a959-285b-423d-a704-fe5798daf2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據'])[1]/preceding::button[1]</value>
      <webElementGuid>8c367b24-26dc-4c7d-9c44-3330a33eab8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>388cbc06-a29f-4177-9b42-7bea3fb3e347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-mapping-btn' and @type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      <webElementGuid>beb7a159-2de6-432c-87b7-bf5da10c93c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
