<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>退回審核說明退回</name>
   <tag></tag>
   <elementGuidId>1d01f37c-04da-4718-be5e-6b949c8200ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class, 'ant-modal')]//div[contains(@class, 'ant-modal-footer')]//button[contains(@class, 'ant-btn-dangerous')][count(. | //*[@type = 'button' and (text() = '退 回' or . = '退 回')]) = count(//*[@type = 'button' and (text() = '退 回' or . = '退 回')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-default.ant-btn-dangerous</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8e44593-efaa-44f8-ac9a-63a4c83d94a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d1eb6c8-a561-4cff-94b8-b7813ac0af4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-dangerous</value>
      <webElementGuid>b1d42f92-f4c7-4f30-bc83-e46559462220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>退 回</value>
      <webElementGuid>606ee9e4-c809-4485-a368-f05247e58576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class, 'ant-modal')]//div[contains(@class, 'ant-modal-footer')]//button[contains(@class, 'ant-btn-dangerous')]</value>
      <webElementGuid>56f0051b-d9c1-40cb-9d97-22436457242c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>5d722000-1cd7-4161-ac3e-8133995f93bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取 消'])[3]/following::button[1]</value>
      <webElementGuid>8c0f4d9d-f41b-4e4a-9b99-ee7795c7fa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='審核說明'])[1]/following::button[2]</value>
      <webElementGuid>a8432eee-6fcb-4799-b02a-4e269f82db0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/button[2]</value>
      <webElementGuid>644d0f8e-6a0e-4f72-96c6-8c884658a0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '退 回' or . = '退 回')]</value>
      <webElementGuid>a3bf1b2c-b0d1-4e05-9641-0c01232cdeb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
