<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode迄</name>
   <tag></tag>
   <elementGuidId>0659ed53-301a-4322-bdc4-b9876262c939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metaId_25 > div.ant-space-item > div > div > div.container___1meJQ > div.input-pane___3ZuAW > input[type=&quot;tel&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//label[text()='段落資訊']/ancestor::div[contains(@class,'ant-form-item-row')]&#xd;
   //tbody//tr[contains(@class,'ant-table-row')])[1]//td[3]//input&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[42]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>292a50c6-1112-4268-8816-2efafefb7225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8ec19723-38af-475e-8a8f-5dd4c99a6031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e4992c10-6d57-40b7-aaeb-7e4c2a3e195b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label[text()='段落資訊']/ancestor::div[contains(@class,'ant-form-item-row')]&#xd;
   //tbody//tr[contains(@class,'ant-table-row')])[1]//td[3]//input&#xd;
</value>
      <webElementGuid>a752bfe6-8dc4-4e24-9bdb-ec94a1adede8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[42]</value>
      <webElementGuid>faec1d53-2d3f-4b32-976f-ce4ce3c604ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_25']/div/div/div/div/div/input</value>
      <webElementGuid>c7dec963-b39e-4cec-98d8-d54c6514266e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>bcbfeabb-ac26-44bb-bd18-92e9a0d369d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>d6e15002-6a9d-41c7-88be-4addb3febc00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
