<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode起</name>
   <tag></tag>
   <elementGuidId>01edece2-5e6d-45d6-9509-0410beb34ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metaId_25 > div.ant-space-item > div > div > div.container___1meJQ > div.input-pane___3ZuAW > input[type=&quot;tel&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//label[text()='段落資訊']/ancestor::div[contains(@class,'ant-form-item-row')]&#xd;
   //tbody//tr[contains(@class,'ant-table-row')])[1]//td[2]//input&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[42]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98b7a9ec-735b-4c50-8b5a-05fe207ed078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>4673ad2c-1fbe-481e-865f-8149edcec71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9202c019-a601-4271-8e95-ef0dc78435f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label[text()='段落資訊']/ancestor::div[contains(@class,'ant-form-item-row')]&#xd;
   //tbody//tr[contains(@class,'ant-table-row')])[1]//td[2]//input&#xd;
</value>
      <webElementGuid>11bd5c09-6bd9-47eb-aeef-f5b1a61e09c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[42]</value>
      <webElementGuid>bb504844-4dc8-4a4d-b535-946346b061cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_25']/div/div/div/div/div/input</value>
      <webElementGuid>7ff4ecdb-0f3e-4deb-a806-6614b96b3c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>f23b7b3b-fda9-4027-b855-d7c1c2cae290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>b25c535f-44ac-4556-95f8-8d4b5802e7ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
