<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>新增</name>
   <tag></tag>
   <elementGuidId>d72ed544-37ce-4e80-bb27-e656ba6e4529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-modal-footer > button.ant-btn.ant-btn-primary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='段落資訊']/ancestor::div[contains(@class,'ant-form-item-row')]//button[span[text()='新增']]&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[44]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bce51c05-4e28-4b3d-8572-2734a91533c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81599622-e951-417c-b65a-9a2b1ae98177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary</value>
      <webElementGuid>75c761fb-7bcb-4a15-8db9-4e78bfae8c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>儲 存</value>
      <webElementGuid>bf6910a8-b636-4dc2-a4da-8fe9f29aa650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='段落資訊']/ancestor::div[contains(@class,'ant-form-item-row')]//button[span[text()='新增']]&#xd;
</value>
      <webElementGuid>36e8659c-f0b9-4f3c-ab6b-55c17abba6cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[44]</value>
      <webElementGuid>9c18cd63-889d-402c-a50a-1accd36c69fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取 消'])[1]/following::button[1]</value>
      <webElementGuid>b5121403-1203-47db-a183-8e334098be15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='沒有檔案'])[2]/following::button[2]</value>
      <webElementGuid>66506cfb-39ce-4be6-9d5c-37cefd8796ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編輯列管'])[1]/preceding::button[2]</value>
      <webElementGuid>53a56b36-9e05-49cc-9bb9-88be03b043bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7f47d269-2f2a-4277-9cfe-8ad7678933ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '儲 存' or . = '儲 存')]</value>
      <webElementGuid>62271532-f31a-4b1d-ab6f-311cc92f4ad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
