<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>審核順位二選單</name>
   <tag></tag>
   <elementGuidId>ab7dc208-eda8-4898-8864-a1169f28b423</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#approvalProcess_2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'search' and @id = 'approvalProcess_1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='approvalProcess_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>547c168a-6a9f-4d76-82df-6fe2dcde3a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d9841991-ef8a-412d-af4b-52c9bb036e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>approvalProcess_1</value>
      <webElementGuid>0e2ab99c-fba8-4901-b718-b9c27818b582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78f444f3-6d74-4d1f-ab95-5fec9e8b9229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-search-input</value>
      <webElementGuid>787a0f49-4127-490d-8db4-254550dd6e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>20a49680-80df-4e82-8b36-0b39feaa2a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>6e5793db-0fd0-4e66-9204-84cf3cbf1e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>approvalProcess_1_list</value>
      <webElementGuid>a49b5d60-8c02-4bbf-86d2-2fe621190607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>3384ca8c-1168-4b40-aec8-27fce6567580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>approvalProcess_1_list</value>
      <webElementGuid>84b3e682-eabd-4d33-aeb9-42ab4cc335d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>approvalProcess_1_list_0</value>
      <webElementGuid>3ac33a9f-facf-4a88-a710-a62fa62476ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>19084ff3-9524-451a-b7bf-b2c65a3da267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca23cdba-57b1-4169-a46d-977981c1c921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approvalProcess_1&quot;)</value>
      <webElementGuid>68111138-d165-49c7-b46a-8293e05b9662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='approvalProcess_1']</value>
      <webElementGuid>e3fd513a-a7ae-49db-8e13-b79a1e611c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/span/input</value>
      <webElementGuid>79b10258-2e80-4b54-913a-2fb4adb1b8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'approvalProcess_1']</value>
      <webElementGuid>923fc708-5854-425a-bb59-4b06394280bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
