<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>編輯元數據配對</name>
   <tag></tag>
   <elementGuidId>0911e18f-2d7e-49c3-8ff5-6f66e8bc8217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-mapping-btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'edit-pm-mapping-table' and @type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-mapping-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9eef9db-da77-4a6a-af89-2a7fc2105999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-pm-mapping-table</value>
      <webElementGuid>83e7e3ec-ced5-481b-819f-9869961e6fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c09ba58d-7bed-41e0-b908-60b39389c4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-sm</value>
      <webElementGuid>c375dff0-6047-46dc-ad16-a9ade9f6dc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>編 輯</value>
      <webElementGuid>a6aa5517-8edc-4a3e-9547-e57570d28e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-mapping-btn&quot;)</value>
      <webElementGuid>f598aa3d-5706-43ff-83af-1f7237bdc25a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-mapping-btn']</value>
      <webElementGuid>a589bfad-197e-465b-bd97-6e1228789226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>bf4892f9-6cbd-49c0-bd78-be840bf2c86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據配對'])[1]/following::button[1]</value>
      <webElementGuid>0bf745c2-a54d-4c83-a441-8df348c038ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共 3 筆資料'])[1]/following::button[3]</value>
      <webElementGuid>c7abc27a-a411-4923-b9cc-1740621f9aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據'])[1]/preceding::button[1]</value>
      <webElementGuid>2f8c4395-62f6-4233-85ec-4669ecb93c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>adfd4971-33d6-4b78-b8ca-3b9f75dd6f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-mapping-btn' and @type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      <webElementGuid>29bd1a08-0480-4403-9bc0-58700a761d94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
