<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>新增</name>
   <tag></tag>
   <elementGuidId>03daeacd-184b-4f20-973a-17caa325122b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='警示卡設定'])[1]/following::button[1][count(. | //*[(text() = '新 增' or . = '新 增')]) = count(//*[(text() = '新 增' or . = '新 增')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-mapping-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-mapping-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85c044a9-e8e2-4e49-a5c0-e570c02beeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-custom-meta-mapping-table</value>
      <webElementGuid>a4e020c1-e3ae-4d84-871c-f3bd18e76756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bafc70b1-78df-4890-82a1-b0a78ee208ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-sm</value>
      <webElementGuid>276e1e95-0fcf-47a6-9db4-11c070c680fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新 增</value>
      <webElementGuid>99c2cbe4-0366-41c0-83e6-5566937d774c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='警示卡設定'])[1]/following::button[1]</value>
      <webElementGuid>a698eb36-cd63-4e03-b689-09c9d1bec168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-mapping-btn']</value>
      <webElementGuid>61edeb3c-f0aa-4c00-8883-0893da1bc1a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>dd91fad5-b455-4c73-9b4e-79b7048f5378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據配對'])[1]/following::button[1]</value>
      <webElementGuid>ac8a4299-2589-461b-a516-40a1709b3076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共 3 筆資料'])[1]/following::button[3]</value>
      <webElementGuid>c963592f-d4c9-478a-8f2c-1387057f0c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據'])[1]/preceding::button[1]</value>
      <webElementGuid>46cc2da4-7a81-429a-a880-793223d3d9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>7beaca27-180d-4db2-92b0-9395efdf7934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-mapping-btn' and @type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      <webElementGuid>fb586368-4283-49fd-8567-be626642c3a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
