<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>新增檔案來源類型</name>
   <tag></tag>
   <elementGuidId>3775bb72-a917-4455-9f5e-da4e01921e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'add-openshare-source-btn' and @type = 'button' and (text() = '新 增' or . = '新 增')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-openshare-source-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-openshare-source-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f3b84a3-f99a-4aed-b5bd-059b0a8b8314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-openshare-source-btn</value>
      <webElementGuid>a2d60013-0312-4308-a1aa-66f68cb6aa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3efc1fbe-7db9-47e5-8ef0-ba3cd92b7666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-sm</value>
      <webElementGuid>38f1b35e-119b-4e3e-adf9-8fe269d8d13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新 增</value>
      <webElementGuid>0a36ce80-d6f6-41ba-aef3-d2d03aeb4f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-openshare-source-btn&quot;)</value>
      <webElementGuid>9853427a-e537-4ba7-a77c-f592c3663b1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-openshare-source-btn']</value>
      <webElementGuid>5cba9af3-a03a-40d9-8c48-32ba00bef0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>3a46442d-31ae-4992-a646-ac2d4b10ef86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='檔案來源類型'])[1]/following::button[1]</value>
      <webElementGuid>1dd83ffd-9957-4ce4-86f5-26528625c6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='無此資料'])[1]/following::button[1]</value>
      <webElementGuid>5c9262a3-b2c4-4feb-b0c2-2937cb056ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='來源'])[1]/preceding::button[1]</value>
      <webElementGuid>7d2d6d8d-e4f5-4a54-a18f-8170f3f400d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/button</value>
      <webElementGuid>5344f0da-9887-42fc-bf27-0b0734f589c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-openshare-source-btn' and @type = 'button' and (text() = '新 增' or . = '新 增')]</value>
      <webElementGuid>4126f9de-42e2-469b-8fca-389fb06cc3d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
