<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>選項內容一</name>
   <tag></tag>
   <elementGuidId>21328729-baeb-49ba-8a31-ed426b694246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='options_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = '輸入選項內容' and @id = 'options_0' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#options_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>547d0c79-76c1-4687-a91d-8824be3b1817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>輸入選項內容</value>
      <webElementGuid>efe3cf87-df5d-4f9b-a0d1-47af4568471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>options_0</value>
      <webElementGuid>9b97c978-8905-4da5-96d5-9fa7671af262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>af375a57-ee50-4558-baa8-8b7455a4f305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>327597c8-8c3a-423c-ad08-679da2b97c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;options_0&quot;)</value>
      <webElementGuid>427c26a5-eef8-4460-8d0e-43226a9a91a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='options_0']</value>
      <webElementGuid>20be27c8-22f4-4944-ad7b-60d1c56bc0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/input</value>
      <webElementGuid>289aa0f7-de03-4298-ad21-c285e4236618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '輸入選項內容' and @id = 'options_0' and @type = 'text']</value>
      <webElementGuid>e9290a9e-04d9-4fe3-9cc8-8dab7b4aee75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
