<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MarkIn</name>
   <tag></tag>
   <elementGuidId>82200b1e-e130-46ee-8d78-ca1540493ef3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'timelineLSliderThumb']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='timelineLSliderThumb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#timelineLSliderThumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cce65c34-11de-45a7-a4f5-6688a9c9346f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timelineLSliderThumb</value>
      <webElementGuid>4c08c02d-ca3f-4dc8-940a-29911aabb7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-thumb___1JylK</value>
      <webElementGuid>a80dfb9d-04d0-4a5d-a911-5bac0fec8dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timelineLSliderThumb&quot;)</value>
      <webElementGuid>593e40bb-1297-445c-9297-c7a55fee92d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='timelineLSliderThumb']</value>
      <webElementGuid>26f9956c-78ad-4d59-8b73-86395e759a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[3]/div[2]/div[2]/div/div[3]</value>
      <webElementGuid>df47fb6d-dd43-4741-91eb-a94e201156a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>c2f06438-2fe3-4652-bbff-8cd7a412c89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'timelineLSliderThumb']</value>
      <webElementGuid>7095dab6-f9ce-4dbe-a8f2-49303b3abe0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
