<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MarkOut</name>
   <tag></tag>
   <elementGuidId>d91b4542-e0dc-4523-a419-1bb84fe64cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'timelineRSliderThumb']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='timelineRSliderThumb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#timelineRSliderThumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>648a5619-3393-4aa0-9ae9-b819302a1ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timelineRSliderThumb</value>
      <webElementGuid>897ff0e5-5af7-423b-9568-823b6225c224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-thumb___1JylK</value>
      <webElementGuid>061a7f45-4e4f-4bc9-964c-1cef0cc2d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timelineRSliderThumb&quot;)</value>
      <webElementGuid>db9a7607-fc54-4649-a1c9-5d572dd717f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='timelineRSliderThumb']</value>
      <webElementGuid>2c780122-6dae-4e2e-92c4-190b7aab556d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[3]/div[2]/div[2]/div/div[4]</value>
      <webElementGuid>975e3c65-20f2-447a-b244-03131fe404bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>9e010c87-aad9-4ffd-aa1c-db9e250b467e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'timelineRSliderThumb']</value>
      <webElementGuid>00d75f5d-1f8b-447b-af22-aaa84d8602ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
