<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>媒資資訊關閉X</name>
   <tag></tag>
   <elementGuidId>fc8b9a2e-7d50-4d62-99be-c509cb79de16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ant-modal-close-x</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>(//span[@class='ant-modal-close-x'])[4]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div[2]/div/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>12c422f8-7229-496e-9e4d-5592bfbf4a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-modal-close-x</value>
      <webElementGuid>dd811e57-5d60-4fec-8d6d-f0cc09db6fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@class='ant-modal-close-x'])[4]</value>
      <webElementGuid>c1d1053d-160c-4cf3-b5dc-aa0bf828e63b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='儲 存'])[2]/following::span[1]</value>
      <webElementGuid>40c9eb6f-61c6-495d-8822-40f74eca08ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取 消'])[2]/following::span[2]</value>
      <webElementGuid>4136e9eb-e939-4d72-9335-d44f0e993f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='媒資分類'])[4]/preceding::span[2]</value>
      <webElementGuid>37462a3e-24b8-468d-9fcd-39ec7e7a3314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='政治'])[8]/preceding::span[2]</value>
      <webElementGuid>dc3ee122-e452-4e35-8e9d-c6f678f6f73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/button[@class=&quot;ant-modal-close&quot;]/span[@class=&quot;ant-modal-close-x&quot;]</value>
      <webElementGuid>88768323-c64c-4ed2-a739-1f1332308999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
