<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>關鍵影格項目2</name>
   <tag></tag>
   <elementGuidId>aa46776f-d206-4d46-ab49-b04a7cbc8457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-0-panel-keyFrame']/div/div/div/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-list-item.item-selected___veD_z</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8da96658-962d-4ae3-bdc8-0e98ea7aadbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-list-item item-selected___veD_z</value>
      <webElementGuid>b1290795-c186-4b10-92a3-f5d61dcd50a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01:00:06:05</value>
      <webElementGuid>9fd3e120-99aa-4b7c-9c83-ab639b096b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-keyFrame&quot;)/div[@class=&quot;ant-list ant-list-split container___NKUDM&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/ul[@class=&quot;ant-list-items&quot;]/li[@class=&quot;ant-list-item item-selected___veD_z&quot;]</value>
      <webElementGuid>84863000-c3c4-4dca-b5ed-0385d2edfacc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-keyFrame']/div/div/div/ul/li[2]</value>
      <webElementGuid>b263ff0e-f3ea-4a7f-a6bd-5a5b508659b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預覽'])[1]/following::li[2]</value>
      <webElementGuid>fc408e56-c307-4f8e-9447-0740196385cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test101'])[9]/following::li[2]</value>
      <webElementGuid>a20832b5-d34b-42fd-94e0-ab5dff3cd7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='主檔資訊:'])[1]/preceding::li[47]</value>
      <webElementGuid>45063475-afa3-4c41-9cf5-13103233b629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='起止影格'])[1]/preceding::li[47]</value>
      <webElementGuid>db1b3739-9026-4ba6-8873-8fea1e6cf948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ul/li[2]</value>
      <webElementGuid>602271db-50bd-405d-956e-1f2db81f806c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '01:00:06:05' or . = '01:00:06:05')]</value>
      <webElementGuid>846b03d0-feb0-4f0b-ac08-f0d5193ef442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
