<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account</name>
   <tag></tag>
   <elementGuidId>45742175-f5a9-45f1-b2c7-cb5bc3aefb3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70b3d3f2-d7ec-4d7d-ace0-3c44c346b93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>輸入帳號</value>
      <webElementGuid>63af2d55-15ff-415b-85c2-5a8580d361a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_username</value>
      <webElementGuid>a6691b7c-5e20-48d2-969c-c524ad433ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fe1ad5a-c82f-4147-9dc3-5db5d8f497b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input input___1qqed</value>
      <webElementGuid>649f3be3-e3e1-4c47-829e-52e380144990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cc09817-56c1-4dfe-b495-f0e0feaf1f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_username&quot;)</value>
      <webElementGuid>9dc4bbac-6607-4ee7-93db-3129806072ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_username']</value>
      <webElementGuid>08102242-86f0-417a-a7e5-d70454831773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div/div/div/div/div/input</value>
      <webElementGuid>766e5769-d49d-44d6-9691-c4427b0e5030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4c8d9875-561e-4f9f-a836-2e9dabe755bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '輸入帳號' and @id = 'basic_username' and @type = 'text']</value>
      <webElementGuid>53fd7615-8628-453c-8cd8-0db36c7147c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
