<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logindomain_check</name>
   <tag></tag>
   <elementGuidId>ff5e1ef1-d713-43bb-9906-564026b8e638</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#basic_isDomainAccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_isDomainAccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4cb547c-e3d8-4cc1-80f8-460e19e5336d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_isDomainAccount</value>
      <webElementGuid>ef8c48ed-4e3e-4587-93ff-4ed845b3b9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
      <webElementGuid>d08185f8-1f10-428a-821c-56795d9c0e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1e145c53-9e8a-40a8-95a2-b316ab354665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_isDomainAccount&quot;)</value>
      <webElementGuid>c95ede0e-362c-432b-a11a-cdba58a77e0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_isDomainAccount']</value>
      <webElementGuid>12c90ab4-6c25-4235-a55d-3741e1cbb6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[4]/div/div/div/div/div/label/span/input</value>
      <webElementGuid>df291c9d-2d3c-422e-9946-f08598e6f9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/input</value>
      <webElementGuid>4b68b80d-baed-46f4-9bdb-d76e7061f22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_isDomainAccount' and @type = 'checkbox']</value>
      <webElementGuid>1880c588-4ced-48bd-aef3-36aa27bd620b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
