<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>媒資權限</name>
   <tag></tag>
   <elementGuidId>8091b113-ea2b-469b-b70a-fd29d18d2101</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'tab' and (text() = '媒資權限' or . = '媒資權限')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-1-tab-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-1-tab-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdd133ea-a083-48c8-8cc6-031fa737bbd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9840e785-7a9d-4198-9bb3-b9cc64a226e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6cdce23-cfb5-4ca6-8bf4-c23db1d7b200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>2729ca1a-0984-444c-bcce-0786d8bb0c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61811fed-efb0-4c1d-ae5f-294084c82689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-1-tab-2</value>
      <webElementGuid>14784ba9-2685-4b5c-9991-8a0fd372b5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-1-panel-2</value>
      <webElementGuid>6f44d14c-b108-4b83-8f0b-270077d5f529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>媒資權限</value>
      <webElementGuid>81f3edba-8315-4454-8c88-6b890ee49cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-2&quot;)</value>
      <webElementGuid>0a47ce8f-952e-409e-9b38-f3f6f2fa54f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-tab-2']</value>
      <webElementGuid>f1dc0279-2ae4-4e69-b10e-75894092025d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='系統權限'])[1]/following::div[2]</value>
      <webElementGuid>cde1d63e-4f8b-4368-9a37-eec7591968c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='角色名稱'])[2]/following::div[15]</value>
      <webElementGuid>6c47a8ea-d6bd-4614-b7c8-5695c6d32d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='所有項目'])[1]/preceding::div[7]</value>
      <webElementGuid>de910aa6-2773-4725-9610-ae0453649d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='媒資權限']/parent::*</value>
      <webElementGuid>08d26994-97e5-4381-8919-2f75bba401a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>d871e2d5-d624-4e45-b3e9-52282f183943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-1-tab-2' and (text() = '媒資權限' or . = '媒資權限')]</value>
      <webElementGuid>c42ea37a-af7a-457a-8160-42217b53c0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
