<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>系統權限</name>
   <tag></tag>
   <elementGuidId>7c3bbd5a-310b-45e7-b6e9-5d069e799dcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-1-tab-1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'rc-tabs-1-tab-1' and (text() = '系統權限' or . = '系統權限')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-1-tab-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef4dc12b-45f2-444b-96cd-831d1c8da00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>70ee4467-2620-4959-b31c-663e41d8fdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b4d241b-79ca-496a-9174-3773d2f0843c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>08a302ba-dde8-494e-a047-07c90835aba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eaaa1db2-69c0-4932-a7ca-15fcbca12ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-1-tab-1</value>
      <webElementGuid>440a56b1-8a31-41cc-96e5-ebf39579e727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-1-panel-1</value>
      <webElementGuid>197f8b8b-35f1-4ef4-a3dc-9455f8ef2a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>系統權限</value>
      <webElementGuid>bca21918-ea83-4003-86d1-416a48401a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-1&quot;)</value>
      <webElementGuid>1e9f82f9-5ae1-47eb-bfd4-b6a7bfd7d83c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-tab-1']</value>
      <webElementGuid>900f15a3-e047-4914-90f8-9198ee43ebf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='角色名稱'])[2]/following::div[13]</value>
      <webElementGuid>dccf1bf5-ee78-4857-a2e5-074a660d60f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新增角色'])[2]/following::div[20]</value>
      <webElementGuid>ebcd1aeb-d5dd-47a7-8374-d72399eed033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='媒資權限'])[1]/preceding::div[1]</value>
      <webElementGuid>19c15182-0fe0-4fba-b737-0f769592960c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='所有項目'])[1]/preceding::div[9]</value>
      <webElementGuid>5b6ad17e-c6df-4988-971f-8e6d8894e00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='系統權限']/parent::*</value>
      <webElementGuid>667ea0d2-ffda-4fa6-9401-9f9bae5f62dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>76e9d810-b66d-41c7-a7e3-f92a4983c443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-1-tab-1' and (text() = '系統權限' or . = '系統權限')]</value>
      <webElementGuid>f051bac7-e6d3-44a6-a1c4-832affb19486</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
