<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openshareIn_search_button</name>
   <tag></tag>
   <elementGuidId>647c2e50-3c5e-47cd-8fa9-bf714072b3ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-openshare-asset-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-openshare-asset-btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;search-openshare-asset-btn&quot;)[count(. | //*[@id = 'search-openshare-asset-btn' and @type = 'button' and (text() = '搜尋' or . = '搜尋')]) = count(//*[@id = 'search-openshare-asset-btn' and @type = 'button' and (text() = '搜尋' or . = '搜尋')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>664f992d-39ee-4c67-a1e0-bd76def96b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-openshare-asset-btn</value>
      <webElementGuid>647469e4-414e-4e26-8640-d5a00bab9842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47005dba-bda1-42ed-ba24-bf3e2dc30dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-background-ghost</value>
      <webElementGuid>0983624c-b5bf-427f-82c0-73228c6a25ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>搜尋</value>
      <webElementGuid>77bd6b88-d84c-4938-9f17-1ec7ca5fe70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-openshare-asset-btn&quot;)</value>
      <webElementGuid>98693eb0-8c12-4582-8bdb-06aae5368967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search-openshare-asset-btn']</value>
      <webElementGuid>9aea07af-8298-4a45-9b1b-738fbb7f66ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='重置'])[2]/following::button[1]</value>
      <webElementGuid>88d3a889-26a1-4499-b3e5-2968a76d032b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='素材時間'])[1]/following::button[2]</value>
      <webElementGuid>4ad7c62d-80ae-4d80-a189-3d5d7ee89baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::button[1]</value>
      <webElementGuid>45faa609-258c-4c31-8b08-a3fe31534298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button</value>
      <webElementGuid>3906e53f-7d17-4d24-b714-37213dd440d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'search-openshare-asset-btn' and @type = 'button' and (text() = '搜尋' or . = '搜尋')]</value>
      <webElementGuid>f3f617c9-280f-4564-b329-5a5bee9b2064</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
