<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>openshareIn_reset_button</name>
   <tag></tag>
   <elementGuidId>ffc6e95c-c3f3-4d78-916f-cafdcca53b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reset-search-openshare-asset-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='reset-search-openshare-asset-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e71e198-0e0d-42e9-b7ae-ff91a6847c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reset-search-openshare-asset-btn</value>
      <webElementGuid>6a91e3ee-13a9-474e-9f7b-378365ea9ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fbfd68b-ab11-4bd8-a9bb-50ab212d7898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default</value>
      <webElementGuid>8c3076d9-e80b-4509-9207-ef15b0336506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>重置</value>
      <webElementGuid>85530b4b-19a9-473d-a5f6-b9183e77de8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reset-search-openshare-asset-btn&quot;)</value>
      <webElementGuid>544b3a90-c43b-4341-8230-1fc96bbd6426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='reset-search-openshare-asset-btn']</value>
      <webElementGuid>06f1cc1c-9df8-444c-8225-7e3d37e91602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='素材時間'])[1]/following::button[1]</value>
      <webElementGuid>76055e18-0be5-4c00-83fa-be438791b1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='請選擇'])[4]/following::button[1]</value>
      <webElementGuid>27f9b3a2-2ff9-4fa8-9ef6-dffb8391f471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='搜尋'])[2]/preceding::button[1]</value>
      <webElementGuid>349ece0d-a687-48c8-a17a-de07c78f2887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>90133217-5461-4e9e-a2fe-0ecef6ae47e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'reset-search-openshare-asset-btn' and @type = 'button' and (text() = '重置' or . = '重置')]</value>
      <webElementGuid>319a54c2-5284-4055-9662-c3bbab6ab1b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
