<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__basic_isDomainAccount</name>
   <tag></tag>
   <elementGuidId>3b8d88a5-d4a0-488a-aea0-d73221282b2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='basic_isDomainAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#basic_isDomainAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f1f5321-fadc-4215-aba9-ccabc7c7f3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>basic_isDomainAccount</value>
      <webElementGuid>cc63b5b3-7ee1-4848-a9fb-1b802b15b873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-checkbox-input</value>
      <webElementGuid>c7aa9d0f-374c-499b-9324-41d0d643b74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>72a6e1b0-196f-4c62-8d0d-7ec8aceda5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_isDomainAccount&quot;)</value>
      <webElementGuid>16eeaf00-77e1-4900-a61f-38cce01877db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='basic_isDomainAccount']</value>
      <webElementGuid>34090e81-1c3f-448f-b1ed-69876a05d699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='basic']/div[4]/div/div/div/div/div/label/span/input</value>
      <webElementGuid>46d08499-e7f1-4644-8d0e-ff2caeeeaac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/input</value>
      <webElementGuid>1cea7f38-d296-4e60-8b2e-66646bbec0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'basic_isDomainAccount' and @type = 'checkbox']</value>
      <webElementGuid>b1fbdb66-4f83-4650-a3fe-49e71f5a6efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
