<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>列表欄位編輯</name>
   <tag></tag>
   <elementGuidId>20d2618b-27e7-49ea-98ea-3573bfad8ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-default.ant-btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd6a91a0-af6b-41a3-9ac9-de3f0bcac58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c61e1ab-9105-44fa-b07a-d9e135dee1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-sm</value>
      <webElementGuid>1ee9604b-66ec-49a0-b855-e85aae2e08ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>編 輯</value>
      <webElementGuid>b9e2ef6f-799d-4f9f-9ac0-40811294f9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/section[@class=&quot;ant-layout ant-layout-has-sider layout___1XhSp&quot;]/main[@class=&quot;ant-layout-content content___2QN8t&quot;]/div[@class=&quot;container___1Xg5s&quot;]/div[@class=&quot;content___1oj37&quot;]/div[1]/div[@class=&quot;body___1QKw2&quot;]/dl[@class=&quot;info-item-wrapper___1jkTq&quot;]/div[@class=&quot;info-item___1TO1Q&quot;]/dd[1]/div[@class=&quot;control-area___2Mhq4&quot;]/button[@class=&quot;ant-btn ant-btn-default ant-btn-sm&quot;]</value>
      <webElementGuid>b65de6b2-ed7b-4e4c-860b-e24f1923cc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>1a8b7d0d-d51d-411a-aa34-d1b5e3e3f864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div/div/dl/div[2]/dd/div/button</value>
      <webElementGuid>0390a2bf-3d4b-4d22-9703-b38573b2ce8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='列表欄位'])[1]/following::button[1]</value>
      <webElementGuid>0ee37fee-b2ce-41a9-bf99-227963d52c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='外觀主題'])[1]/following::button[2]</value>
      <webElementGuid>fa6fd670-b1af-4c0b-b716-45a7a09e0087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='還原預設'])[1]/preceding::button[1]</value>
      <webElementGuid>9fe3df8c-309c-400f-aea1-80b0eee2ab53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>f315cf7e-c0f6-404d-ac6c-686f19841732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      <webElementGuid>c6764019-0ef7-428f-9c05-d577b7709c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
