<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edledit4</name>
   <tag></tag>
   <elementGuidId>245ad6da-51b6-46bd-8972-7a9e8c8735bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edl-edit-btn-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edl-edit-btn-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16e503a6-c75f-419d-8686-3ff0d2f6e5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edl-edit-btn-4</value>
      <webElementGuid>2c6e1bef-cc3f-4ce5-8fca-4abf7ee418a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e99819e5-379b-486f-b944-fb82c23c0fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-icon-only</value>
      <webElementGuid>6889db91-ba59-4240-8efb-caa4c842c609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edl-edit-btn-4&quot;)</value>
      <webElementGuid>0b40082a-4d61-4ffa-814f-c2b1b6f6e8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edl-edit-btn-4']</value>
      <webElementGuid>6be33b0c-b16a-4350-91ae-7e8d2b68061b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div[3]/div/div/div/div/div/div[2]/table/tbody/tr[5]/td[35]/span/div/div[3]/button</value>
      <webElementGuid>1b57641b-1695-44e9-858a-3659bfebbeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LRLR----'])[3]/following::button[3]</value>
      <webElementGuid>b5b9bbda-f788-4e30-a988-8bfdda1ce969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pts10'])[4]/following::button[3]</value>
      <webElementGuid>dee10a0c-6076-4e18-a710-a4bf1aca5ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA'])[2]/preceding::button[2]</value>
      <webElementGuid>e8501afd-1fcf-4338-9306-912fd8703be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='耶誕後台0800(家家)'])[1]/preceding::button[2]</value>
      <webElementGuid>a019de3b-6d78-479b-8803-1029e7bdbe82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[35]/span/div/div[3]/button</value>
      <webElementGuid>bb31b95e-517f-4061-a912-9a0dba5a36d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edl-edit-btn-4' and @type = 'button']</value>
      <webElementGuid>11c67b8b-d327-4244-a333-de32287f3582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
