<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img3</name>
   <tag></tag>
   <elementGuidId>f459fad6-95be-4fde-9fb0-ed30b16fdd10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/main/div/div/div[2]/div/div[2]/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'leftPanel___3fIyY')]//div[contains(@class,'mediaList___3TEMS')]/div[contains(@class,'mediaAssetItem___1IsI0')][3]//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;陸禁酒水0800(大大)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f2916ce-59e8-4837-ac3d-b500437ccbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://10.254.16.101:9100/openmam/2025/11/10/0cfb547e97f74abc93260b0ddd71d4c1/F592F26F1DAAFDD81B955D09D59BD2CBD2222264D0B828BCCEBFE1FE3D9485B6.jpg</value>
      <webElementGuid>33a7673f-df3f-4a4c-8a88-a5de513e2415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>陸禁酒水0800(大大)</value>
      <webElementGuid>9e517d8c-f78f-4fc7-afe0-7cbd73426e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'leftPanel___3fIyY')]//div[contains(@class,'mediaList___3TEMS')]/div[contains(@class,'mediaAssetItem___1IsI0')][3]//img</value>
      <webElementGuid>75f09fe5-cc60-4ca3-b496-fc06e151149f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div/div[2]/div/div[2]/img</value>
      <webElementGuid>3706bc32-f197-4cae-958e-bbd2ec1d5811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='陸禁酒水0800(大大)']</value>
      <webElementGuid>b85b9db6-7109-4dfc-8827-63b12b2a46fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>add9df1e-47c3-46b5-9071-9d44ca28a51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://10.254.16.101:9100/openmam/2025/11/10/0cfb547e97f74abc93260b0ddd71d4c1/F592F26F1DAAFDD81B955D09D59BD2CBD2222264D0B828BCCEBFE1FE3D9485B6.jpg' and @alt = '陸禁酒水0800(大大)']</value>
      <webElementGuid>22b38824-5ea9-4c3d-87bc-a15abba6b6e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
