<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img4</name>
   <tag></tag>
   <elementGuidId>a1cf1d08-554b-4589-b20e-9447ec8ca650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/main/div/div/div[2]/div/div[2]/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>&quot;//div[contains(@class,'mediaList___3TEMS')]/div[contains(@class,'mediaAssetItem___1IsI0')][4]//img&quot;</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;陸禁酒水0800(大大)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1eac76aa-1d6a-4c30-9b1c-0e47432efc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://10.254.16.101:9100/openmam/2025/11/10/0cfb547e97f74abc93260b0ddd71d4c1/F592F26F1DAAFDD81B955D09D59BD2CBD2222264D0B828BCCEBFE1FE3D9485B6.jpg</value>
      <webElementGuid>bfb1d8da-2aad-443e-a5c9-7fc300e5f022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>陸禁酒水0800(大大)</value>
      <webElementGuid>d89d7345-2121-4547-8efc-43da5c760a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>&quot;//div[contains(@class,'mediaList___3TEMS')]/div[contains(@class,'mediaAssetItem___1IsI0')][4]//img&quot;</value>
      <webElementGuid>3d12a17b-c8d0-42c4-b1bb-5a924765ee8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div/div[2]/div/div[2]/img</value>
      <webElementGuid>c249e106-35ac-4a0e-976c-e153cb732e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='陸禁酒水0800(大大)']</value>
      <webElementGuid>a8645fa7-fef4-4624-b010-a28afb15006a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>833a7eb5-bffa-4630-bc24-106a958cb824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://10.254.16.101:9100/openmam/2025/11/10/0cfb547e97f74abc93260b0ddd71d4c1/F592F26F1DAAFDD81B955D09D59BD2CBD2222264D0B828BCCEBFE1FE3D9485B6.jpg' and @alt = '陸禁酒水0800(大大)']</value>
      <webElementGuid>17335204-3f1f-4c93-a071-a7eb8d7f1b4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
