<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>cddf19f4-d277-4d90-9ee3-ae7d5f8619b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-openshare-asset-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-openshare-asset-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cec5f0a3-dfd8-49b4-930b-f508030ef2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-openshare-asset-btn</value>
      <webElementGuid>395d9f7b-f949-4c7e-b915-330a3bfda56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f40401d4-6160-42ce-90cb-e0bc0af3e36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary ant-btn-background-ghost</value>
      <webElementGuid>b31c79e2-682e-4021-8c6c-ccd0ead11939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>搜尋</value>
      <webElementGuid>2f136e2a-badf-46ed-af5e-66f942fc0976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-openshare-asset-btn&quot;)</value>
      <webElementGuid>96a5e4a6-22e3-4ca7-9741-9977c0a639bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='search-openshare-asset-btn']</value>
      <webElementGuid>993d6fa3-7074-442c-94de-5946364c1f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='重置'])[2]/following::button[1]</value>
      <webElementGuid>624550ab-033a-43eb-b969-cbe37e3a771c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='素材時間'])[1]/following::button[2]</value>
      <webElementGuid>2c72362d-076c-40dd-af51-41c1a4dc7f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::button[1]</value>
      <webElementGuid>05ca2683-934d-4f3c-ac1a-ddb372f4da32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/button</value>
      <webElementGuid>6a62a31f-6939-4c38-96cf-f25cdef0ad0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'search-openshare-asset-btn' and @type = 'button' and (text() = '搜尋' or . = '搜尋')]</value>
      <webElementGuid>9da1b512-1ab4-4e86-a12a-f16842bd890e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
