<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ant-input</name>
   <tag></tag>
   <elementGuidId>8be245aa-2d75-4e1a-b02e-df707984acb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-input-affix-wrapper.ant-input-affix-wrapper-focused > input.ant-input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = '輸入檔案名稱' and @class = 'ant-input' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbee666e-1bf6-4098-a745-f6a68e236215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>輸入檔案名稱</value>
      <webElementGuid>a72eabdb-16ef-47ed-bda1-d1a0c1f2cdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>c955e4f6-d822-4bbb-a422-59b7f4f6d7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68712e39-4526-454c-9c73-8e6d0225a7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[5]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;container___3ZEZb&quot;]/div[@class=&quot;container___rORkb&quot;]/div[@class=&quot;field___1v5HH&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused&quot;]/input[@class=&quot;ant-input&quot;]</value>
      <webElementGuid>49a8be24-65db-48d7-9590-c6888312196b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[9]</value>
      <webElementGuid>1c0c0d84-566e-4d2b-aa0b-ce7b8debb5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>fef1b4c6-c680-4460-bf5f-a43e171cfff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '輸入檔案名稱' and @type = 'text']</value>
      <webElementGuid>4bc7c62f-ff6b-444f-94d5-aa5d66ab5ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
