<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__record-duration</name>
   <tag></tag>
   <elementGuidId>367a7e79-4aed-4b9f-9cfe-42b12fe97a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#record-duration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='record-duration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd1d019e-c9ba-43d6-91cc-024e98f6b8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>record-duration</value>
      <webElementGuid>4b92f583-9740-4d7f-b2a1-35157d3de9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請選擇時間</value>
      <webElementGuid>c2c4a946-d3dd-4559-983b-c05dfdc7c285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b831c9e5-0ab1-49b3-bfa5-9547b27f120f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2bf4515f-3b2f-44b8-b27f-5b10ebca9721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;record-duration&quot;)</value>
      <webElementGuid>e89bc098-81e5-46a2-8647-1a8067412710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='record-duration']</value>
      <webElementGuid>565cf649-9aba-4a13-94f2-a02af35a4968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>03d712bc-20b2-4be0-9b27-e7f0d60407d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'record-duration' and @placeholder = '請選擇時間']</value>
      <webElementGuid>e4ad8697-2618-4f18-bfb9-512cfa3ca940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
