<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fileName</name>
   <tag></tag>
   <elementGuidId>4e8a3253-5ca3-4ee6-8e69-48914036e2cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fileName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0acdb644-88dd-4fab-bd33-a45bb13dcef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>輸入檔案名稱</value>
      <webElementGuid>5edce308-94d3-4495-aee9-6866876548de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileName</value>
      <webElementGuid>d81cfb89-00f6-45d0-9071-dbb07f1836c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>333b8640-4ffb-4231-9e02-f970aed1bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e07aaf23-03aa-49e8-baf1-a3f1161b38ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileName&quot;)</value>
      <webElementGuid>affa36bc-ceb3-4a2c-9482-437ea851dbd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileName']</value>
      <webElementGuid>4e302d12-119e-496d-8e3b-0ffc98b0d353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d68c1807-13b9-4787-b53e-7906cabe6b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '輸入檔案名稱' and @id = 'fileName' and @type = 'text']</value>
      <webElementGuid>b678f84b-ac89-47f5-85f6-6f7a4ffccd79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
