<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selector</name>
   <tag></tag>
   <elementGuidId>c7f505dd-214a-4e51-ac8d-0c503b673cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[normalize-space(text())='審核順位一']/ancestor::div[contains(@class,'ant-row')]&#xd;
  //div[contains(@class,'ant-select-selector')]&#xd;
&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approvalProcess_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metaId_-1']/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9fd0dff3-b56e-46b0-98d6-3f187afc5146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selector</value>
      <webElementGuid>61b61eff-4283-4e1b-a056-f184db71e995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>國際I</value>
      <webElementGuid>77958ffb-ed1e-4cea-abfd-dd7c38899944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[normalize-space(text())='審核順位一']/ancestor::div[contains(@class,'ant-row')]&#xd;
  //div[contains(@class,'ant-select-selector')]&#xd;
&#xd;
</value>
      <webElementGuid>f447c1c9-d00b-408c-a197-5fd685ab764e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_-1']/div/div/div/div</value>
      <webElementGuid>ee0c325f-79d4-482c-a088-ceb1db1fdde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='媒資分類'])[3]/following::div[8]</value>
      <webElementGuid>b3f5a1ba-287c-449a-888a-072a98bb3e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='編輯媒資'])[1]/following::div[17]</value>
      <webElementGuid>f1823856-c487-4b45-8d8a-72de89af6f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='名稱'])[2]/preceding::div[1]</value>
      <webElementGuid>68128600-b6e0-491d-8600-65257d1b9566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>2621dc97-b567-4a0e-a46f-752d64e86929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '國際I' or . = '國際I')]</value>
      <webElementGuid>de92fc35-a377-4b76-a4d5-1ee633995597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
