<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>一般編輯</name>
   <tag></tag>
   <elementGuidId>ae8a1d1d-4862-45f2-ad99-f45ae70ba8d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#approvalProcess_1_list_2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='單位主管'])[2]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ef8c3fc-3dfe-49f8-a0c3-1254e76ae37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ef8e878-41fd-463f-839f-76157cb0b78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>b2fe4970-20c2-417c-b537-8912c97516d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>一般編輯</value>
      <webElementGuid>460c37c2-f40a-445d-bc76-e46a908f4465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>一般編輯</value>
      <webElementGuid>2c77b3dd-534d-47d9-8068-79de7705c358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='approvalProcess_1_list']//div[@aria-label='一般編輯']</value>
      <webElementGuid>b3deb9fd-86d4-4b5a-80cd-2f4c9660320e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='單位主管'])[2]/following::div[1]</value>
      <webElementGuid>4c7b7430-334d-4e6c-8823-c0f9da1b3e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='部門主管'])[2]/following::div[3]</value>
      <webElementGuid>db686fb5-26ee-44b3-a153-c3218ee2068f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div/div[3]</value>
      <webElementGuid>65d62344-2213-4d0b-a814-fa3d41a38a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '一般編輯' and (text() = '一般編輯' or . = '一般編輯')]</value>
      <webElementGuid>83cc8030-24fa-486a-9d83-2c067275b911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
