<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>單位主管</name>
   <tag></tag>
   <elementGuidId>737b6e38-762b-47fd-96fd-c5e3e32f2e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'ant-select-dropdown') and not(contains(@class,'ant-select-dropdown-hidden'))]&#xd;
 //div[@class='ant-select-item-option-content' and text()='單位主管']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#approvalProcess_1_list_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='部門主管'])[2]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94197655-f588-4ac9-bf5e-3fed0f845430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>033d81a3-d63e-475a-b7f4-37a61b9a865f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-item-option-content</value>
      <webElementGuid>b7856fbf-8ede-49d5-b435-d7d3fb7abe66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>單位主管</value>
      <webElementGuid>f46a7487-9cf0-406c-b9ec-ef9bb2105c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>單位主管</value>
      <webElementGuid>0c1ff1ed-32fb-44e7-a42a-a41ad9b6a0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'ant-select-dropdown') and not(contains(@class,'ant-select-dropdown-hidden'))]&#xd;
 //div[@class='ant-select-item-option-content' and text()='單位主管']</value>
      <webElementGuid>aedc4dd9-50f3-44e8-aa43-1b991f73012a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='部門主管'])[2]/following::div[1]</value>
      <webElementGuid>83607b72-d9b0-49c9-9b65-5adacd1810c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='一般編輯'])[4]/following::div[17]</value>
      <webElementGuid>b69dd19f-c913-4a08-b38d-30870231f746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='一般編輯'])[5]/preceding::div[2]</value>
      <webElementGuid>127201ae-56e9-44ef-b1f8-eb977653afcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>5b913e12-475c-4be4-af5a-f405e182ee77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = '單位主管' and (text() = '單位主管' or . = '單位主管')]</value>
      <webElementGuid>9e7c3948-a23e-4cc9-ab0d-16d13380034a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
