<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>新增</name>
   <tag></tag>
   <elementGuidId>c95cc0f3-3297-45e6-91ea-1ee5acaa0a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='吸菸卡設定'])[1]/following::button[1][count(. | //*[(text() = '新 增' or . = '新 增')]) = count(//*[(text() = '新 增' or . = '新 增')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit-mapping-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-mapping-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04cdecf2-ef5b-459c-8404-0b06cb86e206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit-custom-meta-mapping-table</value>
      <webElementGuid>6d43ed99-8286-41eb-8752-e6e51cc0f797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb69dabc-7d95-49be-8e9c-167d787b7d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default ant-btn-sm</value>
      <webElementGuid>baab1816-b436-4816-a48d-02491c0e553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新 增</value>
      <webElementGuid>8f2148d4-0b05-4e34-ae23-aa1a247104b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='吸菸卡設定'])[1]/following::button[1]</value>
      <webElementGuid>e4290b88-c3d6-4bab-94c3-cdcab0ce24f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='edit-mapping-btn']</value>
      <webElementGuid>b2c654cb-51fb-47e4-8390-147a632b03f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div[2]/div/div/div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>212bef5a-5682-4837-9df0-0c9558e23e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據配對'])[1]/following::button[1]</value>
      <webElementGuid>f19789d9-524a-4dcb-90a8-3c96dcbbd67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共 3 筆資料'])[1]/following::button[3]</value>
      <webElementGuid>bb829ccb-0144-4054-8d03-c10fa1791241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='元數據'])[1]/preceding::button[1]</value>
      <webElementGuid>e2275526-ed73-4459-8b5b-22b438438ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/button</value>
      <webElementGuid>dc8f5bab-bc53-4bdb-8692-3116f12d58bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'edit-mapping-btn' and @type = 'button' and (text() = '編 輯' or . = '編 輯')]</value>
      <webElementGuid>131acca0-23d1-437d-af4a-c44a1debc9a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
