<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OpenNews</name>
   <tag></tag>
   <elementGuidId>bb4cec7a-502c-4374-ae23-b0f8dfaa3e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-item.ant-menu-item-selected.ant-menu-item-only-child</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'menuitem' and (text() = 'OpenNews' or . = 'OpenNews')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_EXTERNAL-popup']/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3093868f-f7e1-4019-bd14-3fd2598b0d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>6d5b88c4-9564-447d-9ac4-9d296f1568c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f119fec5-6376-4c61-8e27-1039f6446419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-45431-3-SETTING_TYPE_OPENNEWS_CONFIG</value>
      <webElementGuid>b8045fca-9647-4d8c-bd79-7ba4e5979bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child</value>
      <webElementGuid>10dd1d35-26af-4321-88b7-a561c65ec790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OpenNews</value>
      <webElementGuid>ef5f683c-9863-43ef-8ac4-a8668f02927d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_EXTERNAL-popup&quot;)/li[@class=&quot;ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child&quot;]</value>
      <webElementGuid>3b032cdf-9f71-45f8-b41a-030f833903cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OpenShare'])[1]/following::li[1]</value>
      <webElementGuid>905ac4d4-9a69-4d2e-8bee-bec792135b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='外部系統'])[1]/following::li[2]</value>
      <webElementGuid>8ff4a668-1200-4721-8a2b-e9a2a0f5fe0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='系統空間'])[1]/preceding::li[1]</value>
      <webElementGuid>e423e97e-6460-48d4-bc0a-ddac8713a654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[2]</value>
      <webElementGuid>a45c916a-8d39-4f18-afc9-c23ab0ae7f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'OpenNews' or . = 'OpenNews')]</value>
      <webElementGuid>f2db9f0d-0e80-4ce4-9858-cfc212fba720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
