<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>其他媒資設定</name>
   <tag></tag>
   <elementGuidId>396cad61-cff7-41e9-bf6e-e954171e15f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'menuitem' and (text() = '其他媒資設定' or . = '其他媒資設定')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-item.ant-menu-item-active.ant-menu-item-selected.ant-menu-item-only-child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_META-popup']/li[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c64d22d2-cd8c-4a4e-962d-9302b73250e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>779e7b7f-1ad9-4ad9-8e90-77cee75c15d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ea9b2878-e9ee-4cbd-9eb3-b4c465613d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-45431-3-SETTING_TYPE_TEMPLATE</value>
      <webElementGuid>c2a4f7c4-6bf2-4d9a-b540-5618d891b8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child</value>
      <webElementGuid>373781d0-471d-42f8-bdba-291b7dff44be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>其他媒資設定</value>
      <webElementGuid>9778a928-6539-4906-8283-528d8c9a83ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_META-popup&quot;)/li[@class=&quot;ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child&quot;]</value>
      <webElementGuid>468abe01-2196-4123-8e4a-f9765ea99556</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_META-popup']/li[3]</value>
      <webElementGuid>ff3b2872-51f9-4a92-b332-7ba96ad2e8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='預設列表'])[1]/following::li[1]</value>
      <webElementGuid>565d827a-0eb8-47dc-a5ea-b2c3ae0b6fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='詳細資訊'])[1]/following::li[2]</value>
      <webElementGuid>9c41663a-fe67-481a-82bc-a42d32cb5ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='媒資搜尋'])[1]/preceding::li[1]</value>
      <webElementGuid>1bc1d997-2f91-4b5c-a8da-f6c9b5b9f5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/ul/li[3]</value>
      <webElementGuid>98139762-39eb-4a1c-b06c-ffefbcac0888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '預設模板' or . = '預設模板')]</value>
      <webElementGuid>3ee1b43f-f14c-4d56-8f9d-d58fd9984637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
