<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>回調送播</name>
   <tag></tag>
   <elementGuidId>7e3a5099-4925-4f3d-ad33-44a47abdb9e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/main/div/div/ul/li[5]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'menuitem' and (text() = '回調/送播' or . = '回調/送播')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-submenu.ant-menu-submenu-inline.ant-menu-submenu-open.ant-menu-submenu-active > div.ant-menu-submenu-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1394951d-bd6a-4f6d-948e-4ee259367bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>ad167992-6439-44cf-b166-c60384b64bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-submenu-title</value>
      <webElementGuid>1fb12b56-7939-4374-8835-3c6345d3e295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bcfbf1ea-cd64-4953-a0f7-9ce94fff52fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8f0ed92-c0d5-4db9-bd83-44cc94202468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>84eac44b-b220-45ea-99ca-9ad5ab9b3944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_RESTORE_TRANSFER</value>
      <webElementGuid>e6e63027-5ab5-4aae-a3b6-3fe82d0c2a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_RESTORE_TRANSFER-popup</value>
      <webElementGuid>a55a504d-1196-417d-b60f-f6543fd3c5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>回調/送播</value>
      <webElementGuid>b455424a-016e-4ee5-8196-a62a51ee6685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/section[@class=&quot;ant-layout layout___1XhSp&quot;]/main[@class=&quot;ant-layout-content content___2QN8t&quot;]/div[@class=&quot;container___1GLJy&quot;]/div[1]/ul[@class=&quot;ant-menu ant-menu-root ant-menu-inline ant-menu-light&quot;]/li[@class=&quot;ant-menu-submenu ant-menu-submenu-inline ant-menu-submenu-open ant-menu-submenu-active&quot;]/div[@class=&quot;ant-menu-submenu-title&quot;]</value>
      <webElementGuid>6d3f2db0-427b-46e7-b791-74f247cae742</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/main/div/div/ul/li[5]/div</value>
      <webElementGuid>97f8873d-ab91-4789-9d8b-c343a1be82ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='平台登入'])[1]/following::div[1]</value>
      <webElementGuid>610499f1-96fc-4200-b559-65e628a70874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='公告管理'])[1]/following::div[1]</value>
      <webElementGuid>2df3425c-2571-4d29-89b3-b92c1bb6373f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='回調位置'])[1]/preceding::div[1]</value>
      <webElementGuid>c88e2763-ecae-4f86-908b-fcc5b44138f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div</value>
      <webElementGuid>6ebaee3d-681d-41c3-b982-76291f568d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '回調/送播' or . = '回調/送播')]</value>
      <webElementGuid>53bf7a6e-c22a-46f4-a0ba-24fed6c1a669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
