<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>審核流程</name>
   <tag></tag>
   <elementGuidId>745a46a3-6053-4eb0-b58b-72a0982ccf5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_USER-popup']/li[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-item.ant-menu-item-active.ant-menu-item-selected.ant-menu-item-only-child</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'menuitem' and (text() = '審核流程' or . = '審核流程')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b3ad425b-c4b8-42bf-9204-893d85b57291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>2c508e3a-2929-448f-95e8-6a54573e367d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2035c350-8f25-43d3-ac22-abdffd76736c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-45431-3-SETTING_TYPE_SIGN_OFF_CHAIN</value>
      <webElementGuid>e75a8513-a90e-4846-82b0-c5b3aec16eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child</value>
      <webElementGuid>c653e2c3-adc1-4b25-83a9-9f44fa3c3820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>審核流程</value>
      <webElementGuid>e05d86b7-b149-423e-be20-1d256cf9e2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_USER-popup&quot;)/li[@class=&quot;ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child&quot;]</value>
      <webElementGuid>55be4358-528d-467a-acd2-d298e74b4f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_USER-popup']/li[4]</value>
      <webElementGuid>865386bf-6523-472c-b6f3-0aac4a271fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='角色管理'])[1]/following::li[1]</value>
      <webElementGuid>37fb3203-54f4-41fd-919d-111f7ae80acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='資源組別'])[1]/following::li[2]</value>
      <webElementGuid>38ca42fa-9e02-45a2-ae5b-f734bdae10dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='媒資設定'])[1]/preceding::li[1]</value>
      <webElementGuid>73f31add-2a38-400d-80fc-db41715942e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]</value>
      <webElementGuid>89970bf7-b407-491a-b348-d837a68ef4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '審核流程' or . = '審核流程')]</value>
      <webElementGuid>b34b05d3-f00a-4051-ae42-46c015c536f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
