<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>資源組別</name>
   <tag></tag>
   <elementGuidId>6ede225d-d031-4776-a7ab-ce25fb52588a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ant-menu-item.ant-menu-item-active.ant-menu-item-selected.ant-menu-item-only-child</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_USER-popup']/li[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@role = 'menuitem' and (text() = '資源組別' or . = '資源組別')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>22663f59-3151-4a1e-b51f-b6bbf4934b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e6c04cec-93a4-4be7-b81f-5b559eea602c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f1808c02-80cf-4c1e-82a0-dc21036d94a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>rc-menu-uuid-45431-3-SETTING_TYPE_RES_GROUP</value>
      <webElementGuid>9203fa8a-2945-4710-937a-594207926b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child</value>
      <webElementGuid>736bf5f9-a2f2-4e79-b748-090d2bb4f27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>資源組別</value>
      <webElementGuid>886d7ad0-5e6d-4757-835e-993c9686f015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_USER-popup&quot;)/li[@class=&quot;ant-menu-item ant-menu-item-active ant-menu-item-selected ant-menu-item-only-child&quot;]</value>
      <webElementGuid>b617e583-8361-4b88-9f55-98f0805f4634</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='rc-menu-uuid-45431-3-SETTING_TYPE_GROUP_USER-popup']/li[2]</value>
      <webElementGuid>cf214f03-55b2-4273-851f-ca467104e144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用者管理'])[1]/following::li[1]</value>
      <webElementGuid>8c7bec07-b71d-4877-a604-b2215feaf922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='使用者設定'])[1]/following::li[2]</value>
      <webElementGuid>de479f41-cbe6-4b1a-a577-e0ed48e5945c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='角色管理'])[1]/preceding::li[1]</value>
      <webElementGuid>7989ba94-169b-4de1-9447-658bd2547613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]</value>
      <webElementGuid>9e33b603-1907-4db1-8b8a-b8988e51d6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '資源組別' or . = '資源組別')]</value>
      <webElementGuid>812953d3-57df-418d-b7d7-b2c4d3723eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
