<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>個人頭像</name>
   <tag></tag>
   <elementGuidId>5e4e8ac1-6981-4916-89c6-3dd576d02f75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='新聞部'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'ant-avatar ant-avatar-circle ant-avatar-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.anticon.anticon-user > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>61e7a5da-d332-4839-9800-0ffd31d441bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>7c985f97-0f30-4da5-9910-be16b6f31004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>508579e6-546c-4d34-9db4-a33f8fa4a6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>7e8c769b-dd3c-4915-b92c-cf518f6eddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>e6c877a9-9181-4ce0-9988-0c4cb8720741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>4e5a2b0d-68ee-4839-9a02-f16ab07968f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>39b26e70-5de5-496d-b48d-cc6d96edce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>066b88a8-33e0-4962-8199-f3c8b0e45be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@class = 'ant-avatar ant-avatar-circle ant-avatar-icon']</value>
      <webElementGuid>e1baf529-d1d0-41f9-aec0-186521f68046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新聞部'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>c8f605d9-eaf4-435e-ae19-6de6b483f1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新增媒資'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>8efb9daa-dc21-461d-a674-409290bd055e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
