<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>回調清單</name>
   <tag></tag>
   <elementGuidId>2fe5dcad-7193-4ecc-9ab3-2ca6a643c8dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'tab' and (text() = '回調清單' or . = '回調清單')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-0-tab-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rc-tabs-0-tab-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae18c824-a891-45f3-8bd7-ca3f84ad811f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c4ba069a-cf61-4af6-8db6-1f85475905c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a053386b-4a16-4113-bf53-43cbac45f93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>921fe78f-5002-43b8-8273-dad3aea99089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24c49b22-ff47-4c44-9030-6fdef633107f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc-tabs-1-tab-1</value>
      <webElementGuid>174ad083-51e1-4d9e-8905-4ba0aea5d8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc-tabs-1-panel-1</value>
      <webElementGuid>061816da-a16f-4d9f-b6f5-c3cab2141f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>回調清單</value>
      <webElementGuid>fa4390c4-d38a-4351-8ecc-2f0507bfd1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-tab-1&quot;)</value>
      <webElementGuid>44b7b2ac-8aa8-4646-b50c-258ce070ae3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-tab-1']</value>
      <webElementGuid>d26cfe06-aba1-410e-bd4d-781542169d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='登出'])[1]/following::div[18]</value>
      <webElementGuid>4334f62f-acd0-4d58-aaf0-42997fb2f245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='系統設定'])[1]/following::div[18]</value>
      <webElementGuid>ba1825e4-a9b1-4ff9-b0a6-1d54eb1dd396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='送播清單'])[1]/preceding::div[1]</value>
      <webElementGuid>b722ef6a-82de-4f58-a151-940bfb472c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申請回調'])[1]/preceding::div[8]</value>
      <webElementGuid>04017941-859e-45b7-b3e2-015788155207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='回調清單']/parent::*</value>
      <webElementGuid>fd087794-83f0-4c35-8e98-7353aaed0cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>50d15ce4-2f48-4c7a-bbc5-d20c0799acd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'rc-tabs-0-tab-1' and (text() = '回調清單' or . = '回調清單')]</value>
      <webElementGuid>f4fe21d4-6620-480f-b600-207cde4fc278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
