<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode_迄</name>
   <tag></tag>
   <elementGuidId>96571b31-29f5-4fb3-a1ec-239b5b45e968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metaId_25 > div.ant-space-item > div > div > div.container___1meJQ > div.input-pane___3ZuAW > input[type=&quot;tel&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[42]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space(text())='短帶Timecode迄']/ancestor::div[contains(@class,'ant-form-item')]&#xd;
 //input[@type='tel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c8d102c-4d4e-445a-a253-365264ee6512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a638211a-d484-4153-9643-8b1ad370f57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f5c67005-7da0-48e1-be3e-839ba5a8e0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space(text())='短帶Timecode迄']/ancestor::div[contains(@class,'ant-form-item')]&#xd;
 //input[@type='tel']</value>
      <webElementGuid>771bda45-1e9e-41fd-b1dc-8ff72e9ba6a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[42]</value>
      <webElementGuid>59433f76-d4b9-4cb6-88b5-97868f25c215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_25']/div/div/div/div/div/input</value>
      <webElementGuid>84a7abba-dd7a-486f-8173-570622c5e257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>526e90bb-9e97-4ace-abe8-2f3f178f44ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>d833106a-42a5-4036-aa15-f820a03a0d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
