<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode起</name>
   <tag></tag>
   <elementGuidId>2f03a24e-b930-4227-8687-4e4881bbfd34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[42]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space(text())='timecode起']/ancestor::div[contains(@class,'ant-form-item')]&#xd;
//input[@type='tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#metaId_25 > div.ant-space-item > div > div > div.container___1meJQ > div.input-pane___3ZuAW > input[type=&quot;tel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>086c3944-daa1-480d-9fc8-631ffb498c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ffa0eb88-5f9c-4cbc-8c00-96f3240809bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>71120405-3a0c-4813-aee6-5f033371a246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space(text())='timecode起']/ancestor::div[contains(@class,'ant-form-item')]&#xd;
//input[@type='tel']</value>
      <webElementGuid>23b154b4-796e-46a1-89e8-1d4bb126f268</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[42]</value>
      <webElementGuid>ab21104e-7d0f-49b8-8bf5-04fab29f4f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_25']/div/div/div/div/div/input</value>
      <webElementGuid>4f67638c-d0e6-4f78-9bf9-7ef68da6d3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>fd5bc91d-e27a-487b-baf8-3a29282256c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>15ab7341-76d9-48f5-825d-92a2016d481f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
