<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode起2</name>
   <tag></tag>
   <elementGuidId>3652483e-b330-4d8e-a928-71a9d376fe05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[43]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space(text())='timecode起']/ancestor::div[contains(@class,'ant-form-item')]//input[@type='tel'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b393dbb2-34a4-4b34-be39-81ec7622d5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a50e8fd2-e05c-4cb7-b3ca-b48a720fc520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b49c39dd-40cc-4a22-ac67-a1e0241d5db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space(text())='timecode起']/ancestor::div[contains(@class,'ant-form-item')]//input[@type='tel'][2]</value>
      <webElementGuid>507f41a1-4e1d-4761-bfd5-7d575dcee171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[43]</value>
      <webElementGuid>ddbf348c-2280-4458-b0e5-b9819e19a50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_25']/div/div/div/div/div/input[2]</value>
      <webElementGuid>95b34c1b-842a-4d17-beef-d7938f5f2517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div/div/div/div/input[2]</value>
      <webElementGuid>89a2cef0-a024-4e6f-86d9-5e945314254a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>ac75b7ad-b6c2-42f4-bc9d-b76a68a0bdfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
