<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode迄4</name>
   <tag></tag>
   <elementGuidId>57f63c3c-7b26-4b0c-a472-2460e533c5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[49]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7e0bfb0-e4bc-4d3e-b801-0a78097d5c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>22caf55d-6637-4bd1-a5b4-7c9a03153118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ee9a63cd-7fd1-4e3f-99b2-6847fbff30d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metaId_26&quot;)/div[@class=&quot;ant-space-item&quot;]/div[1]/div[1]/div[@class=&quot;container___1meJQ&quot;]/div[@class=&quot;input-pane___3ZuAW&quot;]/input[4]</value>
      <webElementGuid>6e5c8cc8-c747-4b11-8a0d-0b8138ce46be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[49]</value>
      <webElementGuid>76146649-4a18-401a-b502-4d6c7a2e39ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_26']/div/div/div/div/div/input[4]</value>
      <webElementGuid>866f3e8c-c7ba-4bb6-8499-d12dc76bb31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/div/div/div/div/div/div/div/div/input[4]</value>
      <webElementGuid>cfcbb788-067c-477e-9e91-5e6d73261604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>42dbcea7-b055-40e1-a6ac-0f9e7da4c83f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
