<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode迄1</name>
   <tag></tag>
   <elementGuidId>8ffd5845-1d32-4b12-98d7-0b58ae34fe09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[46]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#metaId_26 > div.ant-space-item > div > div > div.container___1meJQ > div.input-pane___3ZuAW > input[type=&quot;tel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0f4a559-9ccf-4175-b51b-263c515262cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>75f49693-2dae-4872-834e-fca924cb4108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>65f2f11f-044c-41da-83a6-cda8aa75cfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metaId_26&quot;)/div[@class=&quot;ant-space-item&quot;]/div[1]/div[1]/div[@class=&quot;container___1meJQ&quot;]/div[@class=&quot;input-pane___3ZuAW&quot;]/input[1]</value>
      <webElementGuid>f2f5c1c7-ec32-464f-bb9c-d7e04167a486</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[46]</value>
      <webElementGuid>b1ede5b3-9470-4dfa-82f0-6ed496944caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_26']/div/div/div/div/div/input</value>
      <webElementGuid>c3922283-1e35-4ba3-a9b2-f1d434eb66e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ed1eb91b-3226-4131-8afe-53be6f21737c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>ab53d901-7eb2-4e51-bd06-394a1ade504c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
