<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>timecode起4</name>
   <tag></tag>
   <elementGuidId>31470e11-7cba-40aa-bed3-30df73846e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[45]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space(text())='timecode起']/ancestor::div[contains(@class,'ant-form-item')]//input[@type='tel'][4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b2c6109-3dcd-4e43-98cc-a0a7e508b5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>fe272283-1910-4527-b307-cf94a232ded9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>241bfc49-4859-423f-ad54-2cad2ab11c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space(text())='timecode起']/ancestor::div[contains(@class,'ant-form-item')]//input[@type='tel'][4]</value>
      <webElementGuid>6cf74daa-610c-4c94-90c5-bb03763e3685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[45]</value>
      <webElementGuid>2a5ff0ea-d635-4085-897b-c95618856192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_25']/div/div/div/div/div/input[4]</value>
      <webElementGuid>bc8318c8-1ddf-4d72-a84f-ce8717771f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div/div/div/div/div/div/div/input[4]</value>
      <webElementGuid>f5387932-657d-4168-94be-6d5cb97a0e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>77f01019-c7d5-40ea-840c-21d6c4341b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
