<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>上傳字幕</name>
   <tag></tag>
   <elementGuidId>2395d9be-2519-40c7-9d65-65ed36263d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='upload']//input[@type='file' and contains(@accept, '.srt')]&#xd;
&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.ant-btn-default.upload-btn___VVBvK</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d6d4b6f-22cb-4a6e-a46a-65137219f57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4abd35f0-6538-419f-8664-f67cb98da970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default upload-btn___VVBvK</value>
      <webElementGuid>3af0a009-f4d3-41c2-a60a-fed574cf9ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>字幕</value>
      <webElementGuid>7d8ba56b-612f-4ec5-88c9-b2abec410b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='upload']//input[@type='file' and contains(@accept, '.srt')]&#xd;
&#xd;
</value>
      <webElementGuid>65f618bb-70af-4f2e-8c9d-0338e1fa5575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>e70cc049-7548-4da2-8559-da0874ad2845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='upload']/div[2]/span/div/span/button</value>
      <webElementGuid>9defe4c2-bef3-4e42-87da-e4959994d820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='影片'])[1]/following::button[1]</value>
      <webElementGuid>7f311559-2a3d-4f75-858d-7230542df737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='上傳檔案'])[1]/following::button[2]</value>
      <webElementGuid>b6756116-875f-454b-9d09-742c7aa99ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='載入中...'])[1]/preceding::button[2]</value>
      <webElementGuid>045c0c2c-a099-4afa-a8b4-7dbb9943e1bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/span/button</value>
      <webElementGuid>8ef7686f-fd09-4fe4-a18e-4e815928a28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '字幕' or . = '字幕')]</value>
      <webElementGuid>f072d830-23d7-48e6-b371-52af1bd04c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
