<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>節目名稱</name>
   <tag></tag>
   <elementGuidId>5329387e-dc4e-4636-b7ae-27c02cfe9ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space(text())='節目名稱']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#metaId_23 > div.ant-space-item > div > textarea.ant-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='metaId_23']/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b2397e2b-24aa-44ab-be0a-6a8afc6d490e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入內容</value>
      <webElementGuid>f6550ea5-0136-464c-9d58-28c50782a3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>1bc6d390-f554-4dd4-8b01-ba1d456c4204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space(text())='節目名稱']</value>
      <webElementGuid>f8a3d0e8-dca7-4c12-a538-1720ce41ca74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metaId_23']/div/div/textarea</value>
      <webElementGuid>8fdf5f30-8554-4bdd-8e83-7859741de93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]/div/div/div/div/div/textarea</value>
      <webElementGuid>fe0fe074-7684-4a4d-b476-18337e460b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '請輸入內容']</value>
      <webElementGuid>0f131f57-6a09-44af-958d-7edbbdb6ac43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
