<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>節目編號</name>
   <tag></tag>
   <elementGuidId>41aca2ee-5458-46c3-8e6a-ee0926b74403</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space(.)='節目編號']/following::textarea[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;metaId_1&quot;)/div[@class=&quot;ant-space-item&quot;]/div[1]/textarea[@class=&quot;ant-input&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#metaId_1 > div.ant-space-item > div > textarea.ant-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ea4609b-f034-4f2f-800e-c8d30e0de9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入內容</value>
      <webElementGuid>b1a1d6bb-f197-4bdc-807d-068f8f1a2b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>8e1e550e-98c3-4ea7-ad9f-7021ffc0ad8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>not match regex</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20250502-20</value>
      <webElementGuid>5e020740-0a39-4b86-83c8-720bb0d48537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space(.)='節目編號']/following::textarea[1]</value>
      <webElementGuid>590a819b-4168-4028-adde-96ed1a2f5612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>VideoID</value>
      <webElementGuid>ec0072dd-fdf5-4e54-9b68-6c43d71f13a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='video id'])[2]/following::textarea[1]</value>
      <webElementGuid>36d5ca04-f9bd-407f-96d0-ae762a74f2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[9]/following::textarea[1]</value>
      <webElementGuid>bffd37d1-1503-467e-b12e-6bcae97477a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='同步文稿'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8e3728f8-ed49-4d13-9b41-35a27cb9e322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='口白'])[2]/preceding::textarea[1]</value>
      <webElementGuid>a35da27b-af0f-42f9-b460-27928a336481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div/div/textarea</value>
      <webElementGuid>77ff53be-005a-4dce-bc4e-a44e9b392d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = '請輸入內容' and (text() = '20250502-20' or . = '20250502-20')]</value>
      <webElementGuid>2bde6e41-dcf0-4469-a5a2-f2225aa1702c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
